# Generated by Django 3.1.7 on 2021-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210820_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariu',
            name='tipu_user',
            field=models.CharField(choices=[('Funsionariu', 'Funsionariu'), ('recepsionit', 'recepsionit')], max_length=200, null=True),
        ),
    ]
